### ISSUE TITLE
模块装好了 测试失败

### ISSUE THREAD

**Issue by zbcdbncsl** [abcz316/rwProcMem33#14]
Connecting rwDriver:/dev/rwProcMem37
GetProcessPidList count1:876
GetProcessPidList count2:876
调用驱动 GetProcessPidList 返回值:1
GetProcessCmdline ioctl():Illegal seek
Segmentation fault

---Start:0x72d10d8000,Size:229376,Type:r--p,Name:/apex/com.android.runtime/bin/linker64
---Start:0x72d1110000,Size:950272,Type:r-xp,Name:/apex/com.android.runtime/bin/linker64
---Start:0x72d11f8000,Size:32768,Type:r--p,Name:/apex/com.android.runtime/bin/linker64
---Start:0x72d1200000,Size:8192,Type:rw-p,Name:/apex/com.android.runtime/bin/linker64
---Start:0x72d1202000,Size:16384,Type:rw-p,Name:
---Start:0x72d1206000,Size:4096,Type:r--p,Name:
---Start:0x72d1207000,Size:24576,Type:rw-p,Name:
---Start:0x7ff1deb000,Size:4096,Type:---p,Name:
---Start:0x7ff1dec000,Size:8384512,Type:rw-p,Name:[stack]
VirtualQueryExFull count 4897
VirtualQueryExFull res 4897
调用驱动 VirtualQueryExFull(只显示在物理内存中的内存) 返回值:1
VirtualQueryExFull 失败
Segmentation fault

**Comment by ATCThunder** [comment]
老哥你是交叉编译的吗，我老是出错，能教一下吗

**Comment by 1400935424** [comment]
我也是一样的问题，显示段错误

**Comment by 1400935424** [comment]
老哥，有解决办法了吗

**Comment by zhuhao666** [comment]
> 
解决了 又遇到兼容性问题  骁龙888 888+ 装模块的验证不知道怎么绕过验证 , 改boot.img就卡死开不了机


> 老哥，有解决办法了吗

**Comment by 1400935424** [comment]
> 解决了 又遇到兼容性问题 骁龙888 888+ 装模块的验证不知道怎么绕过验证 , 改boot.img就卡死开不了机
> 
> > 老哥，有解决办法了吗

老哥，请问你这个 Segmentation fault 问题怎么解决的

**Comment by abcz316** [comment]
The kernel source code does not match the phone
