### ISSUE TITLE
怎么编译和刷入驱动

### ISSUE THREAD

**Issue by AFan4724** [abcz316/rwProcMem33#15]
好兄弟留个联系方式

**Comment by LawOfChenfeng** [comment]
有啥事吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "abcz316/rwProcMem33"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 晚上6:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[abcz316/rwProcMem33] 怎么编译和刷入驱动 (Issue #15)





 
好兄弟留个联系方式

**Comment by AFan4724** [comment]
修改哪些地方，进行适配，怎么编译，直接make吗？怎么跳转指针

**Comment by abcz316** [comment]
Not for people without a foundation
