### ISSUE TITLE
读取失败

### ISSUE THREAD

**Issue by 2265290305** [abcz316/rwProcMem33#16]
![IMG_20230314_134225.jpg](https://user-images.githubusercontent.com/86171566/224907543-4787beae-099d-443f-b263-ee4327b63546.jpg)

![IMG_20230314_134203.jpg](https://user-images.githubusercontent.com/86171566/224907544-875f345c-9e9c-441f-b219-f43eb47431eb.jpg)

**Comment by abcz316** [comment]
Make sure that the kernel source code matches the phone
