### ISSUE TITLE
mm_struct问题

### ISSUE THREAD

**Issue by baipiaoguai123** [abcz316/rwProcMem33#18]
错误：“结构mm_struct”中没有名为“mmap_sem”的成员

**Comment by abcz316** [comment]
Please open the version number macro in the version control header file

**Comment by baipiaoguai123** [comment]
好的，已经解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月10日(星期三) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [abcz316/rwProcMem33] mm_struct问题 (Issue #18)





 
请仔细阅读源代码中的down_read_mmap_lock函数
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;
