### ISSUE TITLE
编译报错 Compilation error 

### ISSUE THREAD

**Issue by round123** [abcz316/rwProcMem33#22]
In file included from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.h:21:0,
from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.c:1:
/home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/phy_mem.h: In function 'get_task_proc_phy_addr':
/home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/phy_mem.h:151:2: error: unknown type name 'p4d_t'
p4d_t *p4d;
^
In file included from ../arch/arm64/include/asm/page.h:37:0,
from ../arch/arm64/include/asm/memory.h:28,
from ../arch/arm64/include/asm/thread_info.h:32,
from ../include/linux/thread_info.h:25,
from ../include/asm-generic/preempt.h:4,
from ./arch/arm64/include/generated/asm/preempt.h:1,
from ../include/linux/preempt.h:59,
from ../include/linux/spinlock.h:50,
from ../include/linux/seqlock.h:35,
from ../include/linux/time.h:5,
from ../include/uapi/linux/timex.h:56,
from ../include/linux/timex.h:56,
from ../include/linux/sched.h:19,
from ../arch/arm64/include/asm/compat.h:25,
from ../arch/arm64/include/asm/stat.h:23,
from ../include/linux/stat.h:5,
from ../include/linux/module.h:10,
from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.h:3,
from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.c:1:
../arch/arm64/include/asm/pgtable-types.h:50:24: error: request for member 'pgd' in something not a structure or union
#define pgd_val(x) ((x).pgd)
^
/home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/phy_mem.h:175:104: note: in expansion of macro 'pgd_val'
printk_debug("pgd_val = 0x%lx pgd addr:0x%lx\n", (unsigned long int)pgd_val(pgd), (unsigned long int)pgd_val(pgd));
^
../arch/arm64/include/asm/pgtable-types.h:50:24: error: request for member 'pgd' in something not a structure or union
#define pgd_val(x) ((x).pgd)
^
/home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/phy_mem.h:176:93: note: in expansion of macro 'pgd_val'
printk_debug("init_mm pgd val:0x%lx,pgd addr:0x%lx\n", (unsigned long)pgd_val((mm->pgd)), pgd_val((mm->pgd)));
^
In file included from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.h:21:0,
from /home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/sys.c:1:
/home/round/stic_kernel_xiaomi_sdm845/out/drivers/rwProcMem33/phy_mem.h:188:2: error: implicit declaration of function 'p4d_offset' [-Werror=implicit-function-declaration]

**Comment by round123** [comment]
交叉编译工具链是gcc 4.9

**Comment by round123** [comment]
内核版本4.9.186

**Comment by abcz316** [comment]
This is a problem with your kernel source code

**Comment by sanqiuu** [comment]
> 内核版本4.9.186

你最后咋解决的
