### ISSUE TITLE
老哥您好，我使用您的驱动失败了

### ISSUE THREAD

**Issue by FaSxxf** [abcz316/rwProcMem33#4]
老哥您好，我使用的是一款自己编译的米8内核且刷入magisk的内核，使用该内核将您的驱动编译出来。
使用insmod非常轻松的就将ko模块刷入到了内核中，且使用lsmod可以确定已经加载了。
但当我使用ndk将您写的testKo.out编译出来后，以root权限运行，发现他读不了任何内存。
![驱动使用失败](https://user-images.githubusercontent.com/87953533/126917595-657470dc-f85c-4d28-b435-d152ca4e8719.png)
然后我自己又写了两个终端程序，一个不断打印变量，一个是使用您的驱动来读写前面程序的变量，发现同样读写不了。
![驱动使用失败2](https://user-images.githubusercontent.com/87953533/126917600-1cc2ce67-fdad-4d0a-942d-279cb19f59e9.PNG)

**Comment by FaSxxf** [comment]
虽然第二张图片有些问题（内存没对上），但是是因为图是后来截取的。
我可以保证！我写的没有问题！

**Comment by liuhe3647** [comment]
你可以去看看驱动源码英文注释部分.....

**Comment by liuhe3647** [comment]
<img width="836" alt="截屏2021-09-01 下午7 22 14" src="https://user-images.githubusercontent.com/19620462/131662918-f6ace6de-61f4-4789-b35e-215fda40893e.png">我这里测试到没有问题...

**Comment by abcz316** [comment]
This problem can be resolved by enabling the macro definition CONFIG_USE_PAGEMAP_FILE in the ver_control.h header file.

**Comment by youHappyOK** [comment]
> 老哥您好，我使用的是一款自己编译的米8内核且刷入magisk的内核，使用该内核将您的驱动编译出来。 使用insmod非常轻松的就将ko模块刷入到了内核中，且使用lsmod可以确定已经加载了。 但当我使用ndk将您写的testKo.out编译出来后，以root权限运行，发现他读不了任何内存。 ![驱动使用失败](https://user-images.githubusercontent.com/87953533/126917595-657470dc-f85c-4d28-b435-d152ca4e8719.png) 然后我自己又写了两个终端程序，一个不断打印变量，一个是使用您的驱动来读写前面程序的变量，发现同样读写不了。 ![驱动使用失败2](https://user-images.githubusercontent.com/87953533/126917600-1cc2ce67-fdad-4d0a-942d-279cb19f59e9.PNG)

解决了吗，遇到一样的问题了

**Comment by abcz316** [comment]
Supported and fixed the crash issue
