### ISSUE TITLE
insmod时遇到No such file or directory错误

### ISSUE THREAD

**Issue by Laulan56** [abcz316/rwProcMem33#7]
![@E5WSTG %5VA65YO7FN%6BO](https://user-images.githubusercontent.com/28177712/133949311-1fee2ad7-0a0d-46a6-b991-45b6f94aed76.png)
使用了绝对路径，可以保证目录下一定存在文件。编写了一个Helloworld的示例模块发现可以成功加载，不知道是否为模块本身问题。

**Comment by abcz316** [comment]
The offset of some kernel variables of onePlus phone is wrong, you need to correct it manually
