### ISSUE TITLE
关于硬件断点多线程的问题

### ISSUE THREAD

**Issue by junknet** [abcz316/rwProcMem33#9]
首先感谢大佬开源的优质代码，小弟拜读之后有些小疑惑。
在对多线程打硬件断点的时候
```c
task = get_pid_task(proc_pid_struct, PIDTYPE_PID);
register_user_hw_breakpoint(&attr, sample_hbp_handler, NULL, task);
```
这应该只是获取到进程中的主线程 task，所以这个断点应该只是对多线程中的主线程有效是吗

**Comment by abcz316** [comment]
不是。当传入的proc_pid_struct为主线程时获取的task即为主线程task，当传入的proc_pid_struct为其他线程时，则对应其他线程的task。在linux内核里主线程与线程统一用pid标识。

**Comment by junknet** [comment]
感谢大佬回复，
目前在想用户空间动态创建（pthread_create）的线程，在内核中怎么拿到对应的task下断点

**Comment by abcz316** [comment]
1./proc/%d/task
2.kernel hook

**Comment by junknet** [comment]
大佬 断点回调函数里面 可以 freeze() 冻结自身吗:)
想实现单步执行

**Comment by enenH** [comment]
单步执行解决了吗
